// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPGqo99IDLiBIKa2PNKRVljmNmWbPY8Ok',
    appId: '1:526509738811:web:b83b1befada11ff2ab051e',
    messagingSenderId: '526509738811',
    projectId: 'ecommerse-e46c5',
    authDomain: 'ecommerse-e46c5.firebaseapp.com',
    storageBucket: 'ecommerse-e46c5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZfamlFg1xoEuwv4Ic0lrTQXQuMIOMt1w',
    appId: '1:526509738811:android:2ddaf9f0708e4963ab051e',
    messagingSenderId: '526509738811',
    projectId: 'ecommerse-e46c5',
    storageBucket: 'ecommerse-e46c5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBEgqxcAlQxYChUI1Tbq_JlvcTCN5ofpY',
    appId: '1:526509738811:ios:1769f5e36f4ddbe4ab051e',
    messagingSenderId: '526509738811',
    projectId: 'ecommerse-e46c5',
    storageBucket: 'ecommerse-e46c5.appspot.com',
    iosClientId: '526509738811-4uuukaisn7p0fa6q6hnkkfl9v2kcf2hg.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBEgqxcAlQxYChUI1Tbq_JlvcTCN5ofpY',
    appId: '1:526509738811:ios:1769f5e36f4ddbe4ab051e',
    messagingSenderId: '526509738811',
    projectId: 'ecommerse-e46c5',
    storageBucket: 'ecommerse-e46c5.appspot.com',
    iosClientId: '526509738811-4uuukaisn7p0fa6q6hnkkfl9v2kcf2hg.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerce',
  );
}
